server:
  port: 9001
polar:
  greeting: Welcome to the local book catalog!

spring:
  application:
    name: catalog-service
#  config:
#    import: "optional:configserver:"
#  cloud:
#    config:
#      uri: http://127.0.0.1:8888
#      request-connect-timeout: 5000
#      request-read-timeout: 5000
#      fail-fast: true
#      retry:
#        max-attempts: 6
#        initial-interval: 1000
#        max-interval: 2000
#        multiplier: 1.1
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5


  cloud:
    config:
      import-check:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: refresh
